name: Repo Sync

on:
  schedule: 
  - cron: "*/2 * * * *" # every 15 minutes. set to whatever interval you like

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: vaibhavmew/Banking-System
        source_branch: main
        destination_branch: repo-sync
        github_token: ${{ secrets.GITHUB_TOKEN }}
